### ISSUE TITLE
Locked drops affected by hoppers and water

### ISSUE THREAD

**Issue by Seercat3160** [Flemmli97/Flan#104]
#### Issue (The better the description the better i can solve the issue):
When a player dies and drops items, they can be picked up using a hopper and water, even if another player can't.

#### Steps to reproduce:
1. Kill a player
2. Attempt to pick up their items (it will not work)
3. Place a hopper
4. Use water to move items into the hopper
5. See items in hopper

#### Affected Versions (Latest is NOT a version):

- Minecraft: 1.17.1
- Fabric(API): 0.42.1+1.17
- Flan: 1.17.1-1.6.2

#### Logs (Use a site like pastebin, gist etc. DONT COPY PASTE THE LOG IN HERE):
https://user-images.githubusercontent.com/76834828/141596114-35a85053-ff1c-46fe-81c1-414053b92587.mp4

**Comment by Flemmli97** [comment]
making them unaffected by water and hopper still has some other points though.
- e.g. if a player then dies over an ocean the drops would sink to the bottom like pre 1.13 instead of floating
- making hoppers unable to pick them up will not prevent it for modded pickup machines

it might be worth it to just simply block hoppers instead of both cause the hopper seem to be a bigger problem

**Comment by Seercat3160** [comment]
Ah, I didn't think of that. This isn't that big of a deal, so if you would like to close this issue, go ahead.

**Comment by Flemmli97** [comment]
k
