### ISSUE TITLE
AE2 Wrench breaking blocks inside claims

### ISSUE THREAD

**Issue by ghost** [Flemmli97/Flan#203]
### Modloader

Forge

### Minecraft version

1.18.2

### Modloader version

FORGE API

### Mod version

1.8.2

### Description

When I use a AE2 Wrench on a claim in AE2 cables they drop.

### Steps to reproduce

1. Step one AE2 Wrench
2. Step two Shift + Right Click on Cables

### Mods that might affect the issue

AE2 + Flan

### Logs

No have log

**Comment by Flemmli97** [comment]
since i dont cancel the `RightClickBlock` event but instead use `setUseBlock` they also need to check `getUseBlock` in 
[https://github.com/AppliedEnergistics/Applied-Energistics-2/blob/forge/1.18.2/src/main/java/appeng/hooks/WrenchHook.java](https://github.com/AppliedEnergistics/Applied-Energistics-2/blob/forge/1.18.2/src/main/java/appeng/hooks/WrenchHook.java) 
before running their logic. that is on them
