### ISSUE TITLE
heads up

### ISSUE THREAD

**Issue by mahjerion** [Flemmli97/Flan#64]
#### Issue (The better the description the better i can solve the issue):
Not really an issue, just a heads up that upgrading from 1.4.2 to 1.5.0 might require users to delete their existing claims - especially true on large servers with many claims. It would get stuck. I have the crash report below.

#### Steps to reproduce:
Upgrade from 1.4.2 and have a very large server with 100's of claims i think?

#### Affected Versions (Latest is NOT a version):
1.5.0

- Minecraft: 1.16.5
- Forge: If forge
- Fabric(API): 35.0
- Flan: 1.5.0

#### Logs (Use a site like pastebin, gist etc. DONT COPY PASTE THE LOG IN HERE):
https://pastebin.com/iwjknanv

**Comment by Flemmli97** [comment]
you sure its flan? since the crashlog sais its age of exile crashing

**Comment by mahjerion** [comment]
Idk but emptying the flan history or downgrading flan fixed it, hmm

**Comment by Wesley1808** [comment]
We just tried updating a relatively large server from 1.4.2 to 1.5.1 and we got the same result. It wouldn't let anyone connect and just get stuck after booting up, freezing the server for about 20 minutes straight with no sign of life. We tried 1.5.0 aswell, and got the same result. I tried this on a test server with barely any claims and could upgrade without any issues though.

No crash reports are attached because there weren't any. Watchdog didn't try to kill the process either.

**Comment by Flemmli97** [comment]
try set inactivityTime in config to -1 to disable the check and see if that is the issue then

**Comment by Wesley1808** [comment]
Just tried this, setting "inactivityTimeDays": -1, in the config file. It still froze. I generated the config file in 1.5.2 to make sure it would read the values correctly. 

Another thing is that after a while, depending on how much memory you allocate to the server, the server will just print this:

[14:23:20] [Netty Server IO #3/WARN]: Unexpected exception from an event executor:
java.lang.OutOfMemoryError: Java heap space
Exception in thread "Netty Server IO #0" [14:23:20] [Netty Server IO #1/WARN]: Unexpected exception from an event executor:
java.lang.OutOfMemoryError: Java heap space
[14:23:20] [Netty Server IO #0/INFO]: [STDERR]: java.lang.OutOfMemoryError: Java heap space

-and stop processing anything altogether.

If necessary, I can help with getting a claims folder large enough to reproduce this behavior.

**Comment by Flemmli97** [comment]
hmmm... yes if you can put the folder as a zip file here that would help

**Comment by Wesley1808** [comment]
Alright, here it is. It only includes the claims on the overworld, but it should be plenty.

Theres also warnings from a "CHORUS" permission. Don't worry about that too much, in all previous versions it was there too, and is (at the very least was) harmless. The reason why its there is because we once really needed a chorus permission, which was before it got implemented into the official build, which had a different ID. It has nothing to do with the official flan jar.
[claims.zip](https://github.com/Flemmli97/Flan/files/6720368/claims.zip)
